import Head from 'next/head'

import { getProducts, getDataHomepage } from '../services/data'
import About from '../components/About'
import Hero from '../components/Hero'
import SubscribeForm from '../components/SubscribeForm'
import HomePlates from '../components/HomePlates'
import HomeSeparator from '../components/HomeSeparator'
import Restaurants from '../components/Restaurants'

export default function Home({ products, dataHome }) {
  return (
    <div>
      <Head>
        <title>Centralfoodmalaga</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Hero />
        <SubscribeForm />
        <HomePlates products={products} dataHome={dataHome[0]} />
        <About />
        <HomeSeparator />
        <Restaurants />
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const products = await getProducts()
  const dataHome = await getDataHomepage()

  return {
    props: { products, dataHome }, // will be passed to the page component as props
  }
}
