import Head from 'next/head'
import Hero from '../components/Hero'
import HomePlates from '../components/HomePlates'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Centralfoodmalaga</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Hero />
        <HomePlates />
      </main>
    </div>
  )
}
